Testimonial
rivasbolinga/massage-caroline pull request #36
Opened 2023-04-23 13:28 UTC by PowerLevel9000

# testimonial with dummy Data

- [ ] star according to costumer 
- [ ] name of customer 
- [ ] hovering effect and beating effect

## happy developing 
![ThumbOkayGIF](https://user-images.githubusercontent.com/116451144/233842504-32defe87-236a-4df5-a739-809612117fd3.gif)

2023-04-23 14:39 UTC, rivasbolinga requested changes
Hi @PowerLevel9000 ! Thank you for your hard work. We are almost there!
I have some changes required. I have seen too many console errors with your project, maybe you should address this issue before merge it.
Also see comments below.
<img width="932" alt="Screenshot 2023-04-23 at 16 40 51" src="https://user-images.githubusercontent.com/103900838/233846167-a5c78f0f-5132-459d-b03e-d12023f1ac89.png">

2023-04-23 14:39 UTC, rivasbolinga commented on src/components/features/home-sliders/Feedback.jsx
> +      <TitleWrap><h2>Customer Feedbacks</h2></TitleWrap>
It would be better if you take the translation word. For that you have to add the new word on the JSON translations files. I believe the French translation is: "client Feedback" but you should double check that.
Also, could you increase a bit the title for desktop version?

2023-04-23 14:39 UTC, rivasbolinga commented on src/components/features/home-sliders/FeedbackCard.jsx
> +      <i className="fa-solid fa-quote-left quote fa-beat" />
To follow our creamy design, it would be better if you choose a colour for the starts that matches de design. Try with a yellow a bit darker.

2023-04-23 14:39 UTC, rivasbolinga commented on src/components/features/home-sliders/Feedback.jsx
> -          img: 'https://dummyimage.com/400x300/fff/7CFC00',
I think we shouldn't have images, because we still don't know how the costumer are going to send their feedbacks. Maybe some will send it but some no?

2023-04-23 16:05 UTC, PowerLevel9000 reviewed
Thanks for suggestions @rivasbolinga i will checkout everything and get back to you soon

2023-04-24 06:16 UTC, rivasbolinga approved these changes
# APPROVED 🟢 🟢🟢🟢🟢

2023-04-24 06:19 UTC, merged